org: alakara

service: sms-game-suite

provider:
  name: aws
  runtime: python3.12 
  stage: dev         
  region: eu-west-1  
  timeout: 30        
  environment:       
    AFRICASTALKING_USERNAME: sandbox
    AFRICASTALKING_API_KEY: atsk_63f6ab496244817dcacc27f53104e2a562c6c21144c159d2040999d227f0aed35629ee0a
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: "arn:aws:logs:${aws:region}:${aws:accountId}:log-group:/aws/lambda/*:*"

functions:
  inboundSmsWebhook:
    handler: handler.inbound_sms_handler # Python file 'handler.py', function 'inbound_sms_handler' - lambda entry point
    events:
      - http:
          path: sms-webhook # The URL path for our webhook
          method: post      
          cors: true        

plugins:
  - serverless-python-requirements 

custom:
  usersTableName: ${self:service}-${sls:stage}-users

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        # Reference the custom variable directly for the table name
        TableName: ${self:custom.usersTableName} # Changed this line
        AttributeDefinitions:
          - AttributeName: phoneNumber
            AttributeType: S
        KeySchema:
          - AttributeName: phoneNumber
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
